"""add phonenumber to user

Revision ID: 5d49e8ec04f4
Revises: aaceb18f8ac5
Create Date: 2022-01-30 18:52:48.719675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d49e8ec04f4'
down_revision = 'aaceb18f8ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
